package rainmanproductions.feedme.userinformation;

public enum InfoType
{
    FIRST_NAME,
    MIDDLE_NAME,
    MIDDLE_INITIAL,
    LAST_NAME,
    BIRTH_DAY_OF_MONTH,
    BIRTH_MONTH,
    BIRTH_YEAR,
    CREDIT_CARD_NUMBER,
    CREDIT_CARD_CSV_NUMBER,
    CREDIT_CARD_EXP_MONTH,
    CREDIT_CARD_EXP_YEAR,
    STREET_ADDRESS,
    DELIVERY_HOME_TYPE,
    DELIVERY_APT_NUMBER,
    DELIVERY_ZIP_CODE,
    DELIVERY_CITY,
    DELIVERY_STATE,
    DELIVERY_COUNTRY,
    EMAIL,
    PHONE_NUMBER,
    BILLING_HOME_TYPE,
    BILLING_APT_NUMBER,
    BILLING_ZIP_CODE,
    BILLING_CITY,
    BILLING_STATE,
    BILLING_COUNTRY;
}
